services:
  web:
    container_name: django_web
    build:
      context: ./tedxlublin
      dockerfile: Dockerfile.prod
    command: gunicorn --config gunicorn_config.py tedxlublin.wsgi:application
    restart: always
    expose:
      - "8000"
    env_file:
      - ./.env.prod
    volumes:
      - static_volume:/home/www/tedxlublin/staticfiles
      - /var/certbot/conf:/etc/letsencrypt:ro

  nginx:
    container_name: nginx_proxy
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/home/www/tedxlublin/staticfiles
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - web-root:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - web

  certbot:
    image: certbot/certbot:latest
    volumes:
      - web-root:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email artpods56@gmail.com --agree-tos --non-interactive -d tedxlublin.rocks -d www.tedxlublin.rocks

volumes:
  static_volume:
  certbot-etc:
  certbot-var:
  web-root:
