version: '3.8'

services:
  web:
    build:
      context: ./tedxlublin
      dockerfile: Dockerfile.prod
    command: gunicorn --config gunicorn_config.py tedxlublin.wsgi:application
    restart: always
    expose:
      - "8000"
    env_file:
      - ./.env.prod
    volumes:
      - static_volume:/home/web/tedxlublin/staticfiles
      - certbot_volume:/var/certbot/conf:/etc/letsencrypt/:ro


  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/home/www/tedxlublin/staticfiles
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - web

  certbot:
    image: certbot/certbot:latest
    volumes:
      - /var/certbot/conf:/etc/letsencrypt/:rw
      - /var/certbot/www/:/var/www/certbot/:rw
    depends_on:
      - nginx
      
volumes:
  static_volume:
