<<<<<<< HEAD
---
=======
>>>>>>> 4d329a1 (Dodane podstrony /newsletter /game m.in.)
version: "3.8"
services:
  web:
    build:
      context: ./tedxlublin
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
<<<<<<< HEAD
      - 8000:8000
=======
      - "8000:8000"
>>>>>>> 4d329a1 (Dodane podstrony /newsletter /game m.in.)
    env_file:
      - ./.env.dev
    container_name: www
    environment:
      - APP_ENV=dev
    restart: always
    volumes:
      - type: bind
        source: ./tedxlublin
<<<<<<< HEAD
        target: /www
=======
        target: /www
>>>>>>> 4d329a1 (Dodane podstrony /newsletter /game m.in.)
